---
- name: install nginx repo
  template: src=nginx.repo.j2 dest=/etc/yum.repos.d/nginx.repo

- name: install nginx
  yum: name={{ nginx_version }} state=present

- name: start nginx and enable on boot
  service: name=nginx state=started enabled=yes

- name: install monit
  yum: name=monit state=present

- name: start monit and enable on boot
  service: name=monit state=started enabled=yes

- name: copy nginx main config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: deploy site specific config
  template: src={{ nginx_vhost }}.conf.j2 dest=/etc/nginx/conf.d/{{ nginx_vhost }}.conf
  notify: reload nginx
