---
- name: Install Nginx, PHP-FPM, NPM and Percona MySQL Client
  hosts: webserver
  remote_user: root
  #accelerate: true

  roles:
    - common
    - percona
    - nginx
    - php-fpm
    - composer
    - npm
