---
- name: Install percona repos
  yum: name=http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm state=present

- name: Install Percona Client
  yum: name={{ item }} state=present
  with_items:
   - Percona-Server-client-56
   - Percona-Server-shared-56

- include: percona-server.yml
  when: install_percona_server == true
