---
- name: Install Percona Server
  yum: name={{ item }} state=present
  with_items:
   - Percona-Server-server-56
  tags:
    - percona-server

- name: create mysql log directory
  file: path=/var/log/mysql state=directory mode=0755 owner=mysql group=mysql

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart percona mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes
