---
- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Disable iptables on boot and stop iptables service
  service: name=iptables state=stopped enabled=no

- name: Set selinux to permissive
  selinux: policy=targeted state=permissive

- name: Install basic packages
  yum: name={{ item }} state=present
  with_items:
    - sysstat
    - wget
    - ntp
    - bind-utils
    - zip
    - unzip
    - rsync
    - openssh-clients
    - mlocate
    - telnet
    - tcpdump

- name: Install epel repos
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present

- name: Install python-keyczar
  yum: name=python-keyczar state=present
